# Generated by Django 6.0.1 on 2026-02-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('Главная', 'Главная'), ('Новости', 'Новости'), ('Ивенты', 'Ивенты')], default='Главная', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(default='Главная'),
            preserve_default=False,
        ),
    ]
