# Generated by Django 6.0.1 on 2026-02-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_likes_post_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('Главная', 'Главная'), ('Новости', 'Новости'), ('Ивенты', 'Ивенты'), ('Другое', 'Другое')], default='Другое', max_length=50),
        ),
    ]
